name: Misha Photo Blog
favicon: null
layout_spectrum: 0.56582
typography_spectrum: 0.27231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#171717'
    - '#009fc5'
    - '#ff777e'
    - '#c50000'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.9184550510253757
  rhythmicContrast: 0.75
purpose: []
