name: Misha Photo Blog
favicon: null
layout_spectrum: 0.50033
typography_spectrum: 0.27231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3fffb'
    - '#221f22'
    - '#b0b8be'
    - '#a46661'
    - '#8d3946'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.9184550510253757
  rhythmicContrast: 0.5546312141232193
purpose: []
